### ISSUE TITLE
`env.reset()` hangs waiting for observation to be returned by `GymAI` agent via Pipe

### ISSUE THREAD

**Issue by Danielhp95** [myt1996/gym-fightingice#2]
Hello FightingICE team!

I am getting a problem trying to `reset()` any of the `FightingIce*` environments. That is, any of the following:

['FightingiceDataNoFrameskip-v0', 'FightingiceDataFrameskip-v0', 'FightingiceDisplayNoFrameskip-v0', 'FightingiceDisplayFrameskip-v0']

I describe the issue below, together with an initial debugging analysis.

I have (unfortunately) replicated this issue in two different machines, one running ArchLinux and the other running Mint 19 (Ubuntu based).

### Problem:

**Setup**:

1. I have installed all python requirements: `py4j, port_for, gym, opencv-python`
2. I have downloaded `FTG4.40` from [Ritsumei's website](http://www.ice.ci.ritsumei.ac.jp/~ftgaic/index-2.html)

**Reproducing the issue**:

The following 4 lines of python code cause the issue to arise

``` python
import gym_fightingice
import gym
env = gym.make('FightingiceDataNoFrameskip-v0',
               java_env_path='correct/path/to/FTG4.40')
env.reset()
```

The call to `env.reset()` never returns. The window displaying the Java running game is stuck at "Now loading..." (picture below).

### Analysis:

The issue seems to be cause by the fact that function `gym_fightingice.envs.FightingiceEnv_Data_NoFrameskip.reset()` gets stuck waiting for an observation from one of the agents:

``` python
# ... inside reset() function in class gym_fightingice.envs.FightingiceEnv_Data_NoFrameskip
190: self.pipe.send("reset")
191: self.round_num += 1
192: obs = self.pipe.recv() # <--- Gets stuck here
193: return obs
```

Line 192 of that function is waiting for the player 1 (stored in `self.p1`) to send an observation to the environment via it's pipe (`self.p1.pipe.send(...)`) so that the environment can receive it (line 192: `self.pipe.recv()`) and return it as the return statement of the `reset()` function.

The script hangs in line 192 because player 1, of class `gym_fightingice.envs.gym_ai.GymAI`. Player 1 is never initialized (function `GymAI.initialize()`) is never called. Furthermore, the `GymAI.processing()` function is never called either. It is in this last function that the player processes the `"reset"` request from the environment, and then sends the observations over to the environment. This behaviour is defined in lines:

``` python
# ... inside processing() function in class gym_fightingice.envs.GymAI
# This function is never called, and hence the environment hangs
79: request = self.pipe.recv()
80: if request == "reset":
81:     self.just_inited = False
82:     self.obs = self.get_obs()
83:     self.pipe.send(self.obs)
```

**Extra information**:

My Java version:  
**Command**: `java -version`:  
**Output**:
```
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-b05)
OpenJDK 64-Bit Server VM (build 25.222-b05, mixed mode)
```

My Python version:  
**Command**: `python --version`:
**Output**: `Python 3.6.6`

Is this a known error? How can I ensure that the required functions are called so that the environment's pipe receives an observation that can return, so that it doesn't hang indefinitely?

Thank you very much for your time and your help. I am more than willing to help on solving this issue and contributing to your codebase!

**Comment by myt1996** [comment]
This repository has moved to the FightingICE official account since 4.40 version. 
See https://github.com/TeamFightingICE/Gym-FightingICE if you are using 4.40 version.
And I think this bug is caused by an additional function in the Java 4.40 version which this version of python API can not handle.
It should work if you switch to the latest version.

In addition, the API should work in all the Linux os but only Ubuntu 18.04 is tested actually.
If you still have a problem, you can try to remove "stdout=devnull, stderr=devnull" in the env you are using to get the full error message of FightingICE Java version and open a new issue under the new repository.
